-- Purpose: Entity-level standardization & conformance (types ok in staging; value harmonization here)
-- Inputs: stg_optimized.patients_std
-- Outputs: xfm.patients (view/table TBA)
-- Notes: join to ref.* mappings; enforce referential checks; no heavy aggregations (those belong to KPIs)
-- TODO: Populate after strategy is locked.
